export { createAdministratorApiClient, isAdministratorPassword } from "@sarmg/admin-web";
export { isAdministratorSession, isAdministratorLoginRequest, isErrorEnvelope } from "@sarmg/contracts";
export { ApiClientError } from "@sarmg/http-client";
export { configureNativeWorkspace } from "./shell/native-workspace.js";
import "@sarmg/design-tokens/tokens.css";
import "@sarmg/design-tokens/tokens.dark.css";
import "@sarmg/design-tokens/reset.css";
import "@sarmg/design-tokens/accessibility.css";
import "./fonts/fonts.css";
import "./appearance/content-blocks.css";
export { default as fontLicenseUrl } from "./fonts/OFL.txt?url";
export { default as cjkFontLicenseUrl } from "./fonts/CJK-LICENSE.txt?url";
